version: "3.9"

services:
  db:
    image: postgres:13
    env_file: .env.test
    restart: always
    container_name: integration-tests
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
